version: "3"
services:

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Anjali12
      - MySQL_USER=root
      - MYSQL_DATABASE=Raj
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
networks:
  default:
    driver: bridge


